// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSmv1LHua5FD39G0Paycsx_4jusXDKehk',
    appId: '1:385758494000:web:dbcd1a327c6fd0f4ffdcf5',
    messagingSenderId: '385758494000',
    projectId: 'group19-bluemuoon',
    authDomain: 'group19-bluemuoon.firebaseapp.com',
    storageBucket: 'group19-bluemuoon.firebasestorage.app',
    measurementId: 'G-M1H81VJWRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-6gIyR5N3zKVGKMzOFRbF9xswnM5CVA',
    appId: '1:385758494000:android:5451f5b3fbdede84ffdcf5',
    messagingSenderId: '385758494000',
    projectId: 'group19-bluemuoon',
    storageBucket: 'group19-bluemuoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxiPNbkp_FBOvulXcCi_ztNOUUJs1lLYY',
    appId: '1:385758494000:ios:ac3af620b3049bceffdcf5',
    messagingSenderId: '385758494000',
    projectId: 'group19-bluemuoon',
    storageBucket: 'group19-bluemuoon.firebasestorage.app',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxiPNbkp_FBOvulXcCi_ztNOUUJs1lLYY',
    appId: '1:385758494000:ios:ac3af620b3049bceffdcf5',
    messagingSenderId: '385758494000',
    projectId: 'group19-bluemuoon',
    storageBucket: 'group19-bluemuoon.firebasestorage.app',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSmv1LHua5FD39G0Paycsx_4jusXDKehk',
    appId: '1:385758494000:web:062e524c4323938fffdcf5',
    messagingSenderId: '385758494000',
    projectId: 'group19-bluemuoon',
    authDomain: 'group19-bluemuoon.firebaseapp.com',
    storageBucket: 'group19-bluemuoon.firebasestorage.app',
    measurementId: 'G-W6JY16CZJ5',
  );
}
